---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-v1
  labels:
    app: app-3
    version: v1
spec:
  selector:
    matchLabels:
      app: app-3
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: app-3
        version: v1
    spec:
      containers:
      - name: myapp
        image: mingrammer/flog:0.4.3
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        command: ["flog", "-l", "-f", "apache_error", "-d", "0.01s"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-v2
  labels:
    app: app-3
    version: v2
spec:
  selector:
    matchLabels:
      app: app-3
      version: v2
  replicas: 3
  template:
    metadata:
      labels:
        app: app-3
        version: v2
    spec:
      containers:
      - name: myapp
        image: mingrammer/flog:0.4.3
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        command: ["flog", "-l", "-f", "apache_error", "-d", "0.01s"]
