---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault
spec:
  vault:
    path: pki/sign/example-dot-com
    server: http://vault.default.svc.cluster.local:8200
    auth:
      kubernetes:
        role: issuer
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: $ISSUER_SECRET_REF
          key: token
