apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: code-server
  namespace: istio-system
spec:
  secretName: code-server-cert
  issuerRef:
    name: letsencrypt-prd
  dnsNames:
  - code.h0n9.postie.chat
